<!DOCTYPE html>
<html>
<head><title>Group5</title>
    <link rel="stylesheet" href="initialStyle.css">
    <link rel="icon" type="image/x-icon" href="https://avatars.githubusercontent.com/u/32927890?v=4">
</head>
<body>
<ul class="headerBar">
    <li class="li">Welcome to the Group 5 Project</li>
    <form action="/" method="POST">
        <input class="li active button" type="submit" value="Home" name="add">
    </form>
    <form action="/rawdata" method="POST">
        <input class="li button" type="submit" value="Raw Data" name="add">
    </form>
    <form action="/button3" method="POST">
        <input class="li button" type="submit" value="Button 3" name="add">
    </form>
</ul>
<div class="main">
    <p>General body of text explaining project???</p>
    <h1>this is a test</h1>
    <marquee width="60%" direction="right" height="100px">
        This is a sample scrolling text that has scrolls texts to right.
    </marquee>
</div>
<div class="footer"><p> RUAIRI DONAGHEY, SHANE GILLIGAN, LAURA GOLEC, PADDI HUA,
    YEVA HUSEVA, KEVIN MORLEY, SAI PRANAY GAMINI, ANNELEE O MAHONY</p></div>
</body>
</html>
